### ISSUE TITLE
Install remains at 0%

### ISSUE THREAD

**Issue by AUyttendaele** [joBr99/nspanel-lovelance-ui#3]
Hi I have tried multiple times but the Nspanel progress bar remains at 0%

Any ideas to how I could continue?
My Tasmota Log File:
[nspanellog.txt](https://github.com/joBr99/nspanel-lovelance-ui/files/8156183/nspanellog.txt)

I am not a developer, I chose your project as node red is something I have worked with and which I feel comfortable using.

Thanks for your support

**Comment by joBr99** [comment]
Which tasmota version do you use?

I'm using this build for nspanel:
https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-nspanel.bin

Also try to flash with the following command, to make sure that it doesn't have something to do with your local webserver:

FlashNextion http://nspanel.pky.eu/lui.tft

**Comment by AUyttendaele** [comment]
Hi, Thanks for your quick help,
It must have been the tasmota version. I used the tasmota32.bin file with a template as suggested in a youtube video.
Thanks for this file. It just flashed without any issue.

One more unrelated question: Are you using the internal temperature sensor? The values are showing at -7 degrees in tasmota.

**Comment by joBr99** [comment]
You can use tasmtoa command "adcparam" for calibration of the temperature sensor, but in general it doesn't seem to be the most reliable temperature source ... the temperature also drifts if the screen is turned on for a while, because of the heat of the screen itself.
