### ISSUE TITLE
Some NodeRed related questions

### ISSUE THREAD

**Issue by gerard33** [joBr99/nspanel-lovelance-ui#4]
Thanks for sharing your excellent dashboard!
Flashed it on the NSPanel and it's looking great 👍 

I am totally new to NodeRed and have some questions you can hopefully help me with.

1. Is it possible to set the time before the screensaver kicks in? I see a msg.payload with `"event,screensaverOpen"` but can't find where to change that.
2. I have added a light in the NodeRed flow for which I would like to receive updates when it's switched on/off from HA on the NSPanel. I have re-used your light event which is connected to `externalUpdates` and if I trigger the light via HA it is being updated correctly showed by the little text under the enity, see the screenshot. I noticed that `externalUpdates` is not connected to anything. I guess that needs to be connected to `pages`?
The code in `externalUpdates` doesn't seem complete. I don't see anything set to the new value.
![image](https://user-images.githubusercontent.com/11230573/156644819-e1e610f7-dc56-46dd-add6-fbebae03b9bc.png)
3. I would like to add a media_player entity which I would like to switch on/off and control the volume via a slider.
I have added the domain in `switch` and added a new call service. Also updated the code in `pages` but I am clearly missing something as it doesn't work. Can you point me in the right direction?

I succeeded in only showing the colortemp slider when the light supports that, so finding my way in Nodered already a bit 😉

```js
function genDetailPage(type, friendlyName){
    var out_msgs = [ ]
    
    let id = searchIdInPages(friendlyName)
    if(type == "popupLight"){
        let switchVal = "0"
        if(global.get("homeassistant.homeAssistant.states['"+id+"'].state") == "on")
            switchVal = "1"
            
        let attr = global.get("homeassistant.homeAssistant.states['"+id+"'].attributes")
            
        let brightness = Math.trunc(scale(attr.brightness, 0, 255, 0, 100))
        
        let colortemp = "disable"
        let attr_support_color = attr.supported_color_modes
        if (attr_support_color.includes("color_temp"))
            colortemp = Math.trunc(scale(attr.color_temp, attr.min_mireds, attr.max_mireds, 0, 100))
        
        out_msgs.push({ payload: "entityUpdateDetail,"+switchVal+","+brightness+","+colortemp})
    }

    return out_msgs
    
}
```

**Comment by joBr99** [comment]
Great to hear, that you like the project :) 

1. time/date command should be implemented on nearly each page and survive page changes
in the example nodered flow time is beeing set through the time string and date string functions, brightness of the screensaver is set through the dimmode commands

2. So far I did not finish implementing external updates in the node red flow, that's the reason why it's not connected to anything 
(and it's also not a top prio for me right now, but if you want to work on it, I will answer you questions, hit me up on unoffical nextion discord server https://discord.gg/98V7qp4)

3. lets discuss this in chat, maybe it's better to add a new page type for this like the thermostat page

4 / colortemp thing

This is great, I added the colortemp thing a few days ago on a feature request, but did not yet add something to the nodered example flow (and I also don't have a light without colortemp but with brightness, so I cannot test this)

**Comment by joBr99** [comment]
@gerard33
 
would add something like this to the display firmware, if it fits your needs (only a mockup, did not implement any of the commands / event messages)
 
![image](https://user-images.githubusercontent.com/29555657/156658299-8d61b454-fa38-41bf-80ea-15d2da03f6fe.png)

**Comment by gerard33** [comment]
The mockup is looking great!
Will send you a message on Discord for the other questions 👍

**Comment by joBr99** [comment]
Media Player moved to seperate issue

**Comment by jorgekramer** [comment]
Still using nspanel with tasmota an nspanel.be. I would like to migrate to nspanel-lovelace-ui completely controlled via Node-Red and MQTT. Is there or will be there a way to do so?

**Comment by jorgekramer** [comment]
Coming back to this issue.
I want controll the nspanel-lovelace-ui via nodered whithout using homeassistant, eg by running the backend python script on nodered python shell.

**Comment by joBr99** [comment]
It is not possible to run the python backend on nodered without Homeassistent or AppDaemon. You need to reimplement the backend yourself if you want to use the firmware like this.

**Comment by joBr99** [comment]
In case you want to go this route, see theese messages for getting started with it:

Message vom Screen in Loading Screen
`event,startup,39,eu` to RESULT topic

Answer from the backend to the CustomSend MQTT Topic (You can also send thoose messages as command on tasmota console for testing)

`time~18:17`
`date~Donnerstag, 25. August 2022`
`timeout~20`
`dimmode~10~100~6371` 

`pageType~screensaver`

touching the panel on the screensaver will result in this MQTT Message on the result topic:

`event,buttonPress2,screensaver,bExit,1`

you can answer this by sending theese commands to the CustomSend Topic

`pageType~cardEntities`

`entityUpd~test~1|1~light~light.schreibtischlampe~X~17299~Schreibtischlampe~0~text~sensor.server_energy_power~Y~17299~Server ENERGY Power~155 W~shutter~cover.rolladenfenster_cover_1~Z~17299~Fenster Eingang~A|B|C|disable|enable|enable~switch~switch.bad~D~63142~Bad~1`

Let me know if you want to do this, it's easier to answer questions to the serial command structure on discord.

**Comment by jorgekramer** [comment]
Thank you for your immediate reply. I come back to this later.

**Comment by jorgekramer** [comment]
Thanks to laluz742 there is now a node-red backend: node-red-contrib-nspanel-lui (currently still in alpha stage)

Will try out.
