### ISSUE TITLE
Can't get ui to work

### ISSUE THREAD

**Issue by guandeag** [joBr99/nspanel-lovelance-ui#5]
I downloaded your ui because i previously tried to do it via esphome which did not work. So i tought lets give tasmota a shot, i have uploaded the tft but it is only showing the page forward and backward keys. Any fix for this?

**Comment by joBr99** [comment]
Sound's like you did not setup the node-red backup stuff?

**Comment by guandeag** [comment]
im kinda new to this so that could very well be possible

**Comment by guandeag** [comment]
could u maybe explain in short what i need to do in node red to make it work?

**Comment by joBr99** [comment]
the nspanel need's to receive commands with the content that should be displayed, this is currently done through a node red flow, there is an example flow in the repo that you can import into your nodered (you will have to adjust mqtt server/password and the topic to your tasmota device)

**Comment by guandeag** [comment]
thanks, i will try it asap!

**Comment by guandeag** [comment]
i have added the flow to node-red and changed the password and server ip, and also the topic for the device but it is still not showing anything except (see screenshot)
![20220304_133936](https://user-images.githubusercontent.com/100923136/156765184-7802d2d6-374f-4ddd-b306-a7d3cb2e1373.jpg)
.

**Comment by joBr99** [comment]
Do you see the messages from the panel in nodered? Pressing the navigation button's is sending a message like "page,x" via mqtt

**Comment by guandeag** [comment]
i am getting the page info on the tasmota console but not in the nodered panel

**Comment by joBr99** [comment]
Sounds like something with your mqtt connection isn't working the messages have to arrive in nodered.

**Comment by guandeag** [comment]
in the log of mostquitto mqtt it does say that nodered has a socket error could that be it?

**Comment by joBr99** [comment]
Yes, check your mqtt config in node red

**Comment by guandeag** [comment]
im forgot to put in the password and username because im a dumbass now it works
