### ISSUE TITLE
Thanks for the template and some suggestions

### ISSUE THREAD

**Issue by Dattel** [joBr99/nspanel-lovelance-ui#6]
Hi there,

i really like the way, you are dealing with getting content to the NSPanel... i've testes some other implementations with esphome, but find it complicated to get content to the Panel... So i'm currently trying out your project.
But i realized, that tasmota has a delay between triggering the physical button and switching the relay... 

So first of all: thanks for your idea :-D

- currently i cheated a bit, when a page does not contain 4 elements and added a "delete.me" item... Is that the correct way to have an empty item?

```
        items: [
            "switch.esstisch", 
            "switch.kuchenschrank",
            "sensor.rf433_temp_wohnzimmer",
            "delete.me"
            ]
```
- would be nice 
     - to have mediacontrol (already mentions in another issue), 
     - dim-settings, 
     - maybe swipes instead of paging, 
     - cool weatherpage?
- external updates currently not working for me :-/
- i added support for "input_boolead" for me - maybe you find it usefull and adapt that for your template. (just small changes on the pages and switch node)

What is the purpose of the newly added appdaemon and how to use it?

**Comment by joBr99** [comment]
- yes, delete is the correct way to have an empty item, but you don't need the .me, just "delete" should be sufficient.
- media control is work in progress
- setting brightness (of the screensaver page) is possible though the "dimmode,x" command
- there is a testpage for swipes in the project (which you can already access press 10 times or so on the "invisible" button left to the navigation buttons), but sadly it seems like the nspanel isn't powerful enough / capable of doing this on the entities page :(
- external updates are not implemented in the nodered flow

Appdeamon is a Homeassiant Add-on, which enables to write automations in python.

https://appdaemon.readthedocs.io/en/latest/HASS_TUTORIAL.html

This is way better for handling the messages of nspanel (and things like external updates) and I'm currently reimplementing the node-red flow in an appdaemon app.

It's currently only handling the pages itself (no button events, no detail pages)
So at the time not yet really usable :)
I will update the readme after it has the current functionality of the nodered flow.

**Comment by Dattel** [comment]
thanks for your reply..
could try with some testings or ideas... 

Regarding the swipe: other projects manage to make it working really smoth... the solution i tried before works pretty well with swipes - but is much more complicated adding devices on the screen.

So user experience would be:
-left/right: change pages
-up/down: maybe homescreen with clock/calendar/temperature option?!? or setting page for dimming/sleeptimes or something else.

**Comment by joBr99** [comment]
Yeah, I've also seen the german in your items array :)
Are you on discord?
Hit me up on the unoffical nextion discord. https://discord.gg/98V7qp4
I think that might be better to discuess this.

I had the swipe stuff implemented (and the working test page is still in the project), but for some reasons it didn't work on the cardEntities Page.
But try yourself, I would be happy to have swipe support.

**Comment by joBr99** [comment]
created an issue for the weatherpage
